// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package org.zhenchao.raft;

public interface AppendEntriesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.zhenchao.raft.AppendEntriesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .org.zhenchao.raft.Partner leaderId = 1;</code>
   */
  boolean hasLeaderId();
  /**
   * <code>required .org.zhenchao.raft.Partner leaderId = 1;</code>
   */
  org.zhenchao.raft.Partner getLeaderId();
  /**
   * <code>required .org.zhenchao.raft.Partner leaderId = 1;</code>
   */
  org.zhenchao.raft.PartnerOrBuilder getLeaderIdOrBuilder();

  /**
   * <code>required int64 term = 2;</code>
   */
  boolean hasTerm();
  /**
   * <code>required int64 term = 2;</code>
   */
  long getTerm();

  /**
   * <code>required int64 prevLogTerm = 3;</code>
   */
  boolean hasPrevLogTerm();
  /**
   * <code>required int64 prevLogTerm = 3;</code>
   */
  long getPrevLogTerm();

  /**
   * <code>required int64 prevLogIndex = 4;</code>
   */
  boolean hasPrevLogIndex();
  /**
   * <code>required int64 prevLogIndex = 4;</code>
   */
  long getPrevLogIndex();

  /**
   * <code>repeated .org.zhenchao.raft.LogEntry entry = 5;</code>
   */
  java.util.List<org.zhenchao.raft.LogEntry> 
      getEntryList();
  /**
   * <code>repeated .org.zhenchao.raft.LogEntry entry = 5;</code>
   */
  org.zhenchao.raft.LogEntry getEntry(int index);
  /**
   * <code>repeated .org.zhenchao.raft.LogEntry entry = 5;</code>
   */
  int getEntryCount();
  /**
   * <code>repeated .org.zhenchao.raft.LogEntry entry = 5;</code>
   */
  java.util.List<? extends org.zhenchao.raft.LogEntryOrBuilder> 
      getEntryOrBuilderList();
  /**
   * <code>repeated .org.zhenchao.raft.LogEntry entry = 5;</code>
   */
  org.zhenchao.raft.LogEntryOrBuilder getEntryOrBuilder(
      int index);

  /**
   * <code>required int64 committedIndex = 6;</code>
   */
  boolean hasCommittedIndex();
  /**
   * <code>required int64 committedIndex = 6;</code>
   */
  long getCommittedIndex();
}
