// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package org.zhenchao.raft;

public interface ErrorInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.zhenchao.raft.ErrorInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 code = 1;</code>
   */
  boolean hasCode();
  /**
   * <code>required int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>optional string desc = 2;</code>
   */
  boolean hasDesc();
  /**
   * <code>optional string desc = 2;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>optional string desc = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
