// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package org.zhenchao.raft;

public interface LogEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.zhenchao.raft.LogEntry)
    com.google.protobuf.MessageOrBuilder {
}
