// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package org.zhenchao.raft;

public interface PartnerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.zhenchao.raft.Partner)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .org.zhenchao.raft.Endpoint endpoint = 1;</code>
   */
  boolean hasEndpoint();
  /**
   * <code>required .org.zhenchao.raft.Endpoint endpoint = 1;</code>
   */
  org.zhenchao.raft.Endpoint getEndpoint();
  /**
   * <code>required .org.zhenchao.raft.Endpoint endpoint = 1;</code>
   */
  org.zhenchao.raft.EndpointOrBuilder getEndpointOrBuilder();

  /**
   * <code>required string groupId = 2;</code>
   */
  boolean hasGroupId();
  /**
   * <code>required string groupId = 2;</code>
   */
  java.lang.String getGroupId();
  /**
   * <code>required string groupId = 2;</code>
   */
  com.google.protobuf.ByteString
      getGroupIdBytes();

  /**
   * <code>optional int32 priority = 3;</code>
   *
   * <pre>
   * election priority
   * </pre>
   */
  boolean hasPriority();
  /**
   * <code>optional int32 priority = 3;</code>
   *
   * <pre>
   * election priority
   * </pre>
   */
  int getPriority();
}
