// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package org.zhenchao.raft;

public interface RequestVoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.zhenchao.raft.RequestVoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .org.zhenchao.raft.Partner candidateId = 1;</code>
   */
  boolean hasCandidateId();
  /**
   * <code>required .org.zhenchao.raft.Partner candidateId = 1;</code>
   */
  org.zhenchao.raft.Partner getCandidateId();
  /**
   * <code>required .org.zhenchao.raft.Partner candidateId = 1;</code>
   */
  org.zhenchao.raft.PartnerOrBuilder getCandidateIdOrBuilder();

  /**
   * <code>required int64 term = 2;</code>
   */
  boolean hasTerm();
  /**
   * <code>required int64 term = 2;</code>
   */
  long getTerm();

  /**
   * <code>required int64 lastLogTerm = 3;</code>
   */
  boolean hasLastLogTerm();
  /**
   * <code>required int64 lastLogTerm = 3;</code>
   */
  long getLastLogTerm();

  /**
   * <code>required int64 lastLogIndex = 4;</code>
   */
  boolean hasLastLogIndex();
  /**
   * <code>required int64 lastLogIndex = 4;</code>
   */
  long getLastLogIndex();

  /**
   * <code>required .org.zhenchao.raft.Partner targetPartner = 5;</code>
   */
  boolean hasTargetPartner();
  /**
   * <code>required .org.zhenchao.raft.Partner targetPartner = 5;</code>
   */
  org.zhenchao.raft.Partner getTargetPartner();
  /**
   * <code>required .org.zhenchao.raft.Partner targetPartner = 5;</code>
   */
  org.zhenchao.raft.PartnerOrBuilder getTargetPartnerOrBuilder();

  /**
   * <code>optional bool preVote = 6 [default = false];</code>
   */
  boolean hasPreVote();
  /**
   * <code>optional bool preVote = 6 [default = false];</code>
   */
  boolean getPreVote();
}
