// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package org.zhenchao.raft;

public interface RequestVoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.zhenchao.raft.RequestVoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 term = 1;</code>
   */
  boolean hasTerm();
  /**
   * <code>required int64 term = 1;</code>
   */
  long getTerm();

  /**
   * <code>required bool granted = 2;</code>
   */
  boolean hasGranted();
  /**
   * <code>required bool granted = 2;</code>
   */
  boolean getGranted();

  /**
   * <code>optional .org.zhenchao.raft.ErrorInfo errorInfo = 3;</code>
   */
  boolean hasErrorInfo();
  /**
   * <code>optional .org.zhenchao.raft.ErrorInfo errorInfo = 3;</code>
   */
  org.zhenchao.raft.ErrorInfo getErrorInfo();
  /**
   * <code>optional .org.zhenchao.raft.ErrorInfo errorInfo = 3;</code>
   */
  org.zhenchao.raft.ErrorInfoOrBuilder getErrorInfoOrBuilder();
}
